name: Notify Non-Committers via Hostinger SMTP

on:
  workflow_dispatch:

jobs:
  list-collaborators-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt update && sudo apt install -y gh

      - name: Fetch Collaborators
        run: |
          echo "Fetching Collaborators..."
          gh api repos/${{ github.repository }}/collaborators --paginate --jq '.[].login' > collaborators.txt
          echo "Collaborators fetched successfully."

      - name: Fetch Committers (Last 24 Hours)
        run: |
          SINCE=$(date -u -d "24 hours ago" +"%Y-%m-%dT%H:%M:%SZ")
          echo "Fetching Users who committed in the last 24 hours..."
          gh api repos/${{ github.repository }}/commits?since=$SINCE --paginate --jq '.[].author.login' | sort -u > committers.txt
          echo "Committers fetched successfully."

      - name: Find Non-Committers
        run: |
          echo "Finding Collaborators who did NOT commit today..."
          sort collaborators.txt -o collaborators.txt
          sort committers.txt -o committers.txt
          comm -23 collaborators.txt committers.txt > non_committers.txt
          echo "Non-committers identified."

      - name: Fetch Emails of Non-Committers
        run: |
          > user_emails.txt
          while IFS= read -r user; do
            echo "Fetching email for $user..."
            EMAIL=$(gh api users/$user --jq '.email')

            if [ "$EMAIL" == "null" ] || [ -z "$EMAIL" ]; then
              EMAIL="${user}@users.noreply.github.com"
            fi

            echo "$user=$EMAIL" >> user_emails.txt
            echo "Email fetched for $user: $EMAIL"
          done < non_committers.txt


      - name: Install and Configure msmtp
        run: |
          sudo apt-get update && sudo apt-get install -y msmtp
          
          echo "Creating msmtp config file..."
          cat <<EOF > ~/.msmtprc
          defaults
          auth           login
          tls            on
          tls_trust_file /etc/ssl/certs/ca-certificates.crt
          logfile        ~/.msmtp.log
          account hostinger
          host smtp.hostinger.com
          port 465
          user "${{ secrets.EMAIL_USERNAME }}"
          password "${{ secrets.EMAIL_PASSWORD }}"
          from "${{ secrets.EMAIL_USERNAME }}"
          auth login
          tls on
          account default : hostinger
          EOF
          chmod 600 ~/.msmtprc

      - name: Send Email to Non-Committers
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        run: |
          while IFS= read -r line; do
            user=$(echo $line | cut -d= -f1)
            EMAIL_TO=$(echo $line | cut -d= -f2)
            echo "Sending email to $EMAIL_TO..."
            echo -e "Subject: Reminder - No Commit Today!\n\nHello ${user},\n\nYou haven't committed to the repository today. Please make sure to contribute.\n\nBest,\nDevOps Team" | msmtp --from=$EMAIL_USERNAME --host=smtp.hostinger.com --port=587 --auth=on --tls=on --user=$EMAIL_USERNAME --passwordeval "echo ${{ secrets.EMAIL_PASSWORD }}" "$EMAIL_TO"
          done < user_emails.txt

      - name: Send Summary Email to Admin
        env:
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        run: |
          NON_COMMITTED_LIST=$(cat non_committers.txt | tr '\n' ', ')
          echo -e "Subject: Daily Commit Report\n\nThe following users did not commit today:\n$NON_COMMITTED_LIST" | msmtp --from=$EMAIL_USERNAME --host=smtp.hostinger.com --port=587 --auth=on --tls=on --user=$EMAIL_USERNAME --passwordeval "echo ${{ secrets.EMAIL_PASSWORD }}" "$RECIPIENT_EMAIL"
