name: Notify Non-Committers via Hostinger SMTP

on:
  workflow_dispatch:  # Allows manual execution

jobs:
  list-collaborators-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch Collaborators
        id: collaborators
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching Collaborators..."
          COLLABORATORS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                              -H "Accept: application/vnd.github.v3+json" \
                              "https://api.github.com/repos/${{ github.repository }}/collaborators" | jq -r '.[].login')
          echo "All Collaborators:"
          echo "$COLLABORATORS"
          echo "$COLLABORATORS" > collaborators.txt
      - name: Fetch Today's Committers
        id: committers
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TODAY=$(date -u +"%Y-%m-%dT")
          echo "Fetching Users who committed today..."
          
          COMMITTERS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                             -H "Accept: application/vnd.github.v3+json" \
                             "https://api.github.com/repos/${{ github.repository }}/commits?since=${TODAY}00:00:00Z" | jq -r '.[].author.login' | sort -u)
          echo "Users who committed today:"
          echo "$COMMITTERS"
          echo "$COMMITTERS" > committers.txt
      - name: Find Collaborators Who Did Not Commit Today
        id: non_committers
        run: |
          echo "Finding Collaborators who did NOT commit today..."
          
          NOT_COMMITTED=$(comm -23 <(sort collaborators.txt) <(sort committers.txt))
          echo "Users who did NOT commit today:"
          echo "$NOT_COMMITTED"
          echo "$NOT_COMMITTED" > non_committers.txt

      - name: Fetch Emails of Users
        run: |
          > user_emails.txt
          while IFS= read -r user; do
            echo "Fetching email for $user..."
            EMAIL=$(gh api users/$user --jq '.email')

            if [ "$EMAIL" == "null" ] || [ -z "$EMAIL" ]; then
              EMAIL="${user}@users.noreply.github.com"
            fi

            echo "$user=$EMAIL" >> user_emails.txt
            echo "Email fetched for $user: $EMAIL"
          done < all_users.txtitters.txt

      - name: Install and Configure msmtp
        run: |
          sudo apt-get update && sudo apt-get install -y msmtp
          
          echo "Creating msmtp config file..."
          cat <<EOF > ~/.msmtprc
          defaults
          auth           login
          tls            on
          tls_trust_file /etc/ssl/certs/ca-certificates.crt
          logfile        ~/.msmtp.log
          account hostinger
          host smtp.hostinger.com
          port 465
          user "${{ secrets.EMAIL_USERNAME }}"
          password "${{ secrets.EMAIL_PASSWORD }}"
          from "${{ secrets.EMAIL_USERNAME }}"
          auth login
          tls on
          account default : hostinger
          EOF
          chmod 600 ~/.msmtprc
      - name: Send Email to Non-Committers
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        run: |
          while IFS= read -r user; do
            EMAIL_TO="pratham.chatke@thedatatechlabs.com"  # Update this based on actual email format
            echo "Sending email to $EMAIL_TO..."
            echo -e "Subject: Reminder - No Commit Today!\n\nHello ${user},\n\nYou haven't committed to the repository today. Please make sure to contribute.\n\nBest,\nDevOps Team" | msmtp --from=$EMAIL_USERNAME --host=smtp.hostinger.com --port=587 --auth=on --tls=on --user=$EMAIL_USERNAME --passwordeval "echo ${{ secrets.EMAIL_PASSWORD }}" "$EMAIL_TO"
          done < non_committers.txt
      - name: Send Summary Email to Admin
        env:
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        run: |
          NON_COMMITTED_LIST=$(cat non_committers.txt | tr '\n' ', ')
          echo -e "Subject: Daily Commit Report\n\nThe following users did not commit today:\n$NON_COMMITTED_LIST" | msmtp --from=$EMAIL_USERNAME --host=smtp.hostinger.com --port=587 --auth=on --tls=on --user=$EMAIL_USERNAME --passwordeval "echo ${{ secrets.EMAIL_PASSWORD }}" "$RECIPIENT_EMAIL"
