name: List Collaborators & Commit Activity

on:
  workflow_dispatch:

jobs:
  list-collaborators-and-committers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch Collaborators
        id: collaborators
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching Collaborators..."
          COLLABORATORS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                              -H "Accept: application/vnd.github.v3+json" \
                              "https://api.github.com/repos/${{ github.repository }}/collaborators" | jq -r '.[].login')

          echo "All Collaborators:"
          echo "$COLLABORATORS"
          echo "$COLLABORATORS" > collaborators.txt

      - name: Fetch Emails of Collaborators
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching Emails of Collaborators..."
          while read -r user; do
            email=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                          -H "Accept: application/vnd.github.v3+json" \
                          "https://api.github.com/users/$user" | jq -r '.email')

            if [[ "$email" != "null" ]]; then
              echo "$user: $email"
              echo "$user: $email" >> collaborators_with_emails.txt
            else
              echo "$user: Email not available"
              echo "$user: Email not available" >> collaborators_with_emails.txt
            fi
          done < collaborators.txt

      - name: Fetch Today's Committers
        id: committers
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TODAY=$(date -u +"%Y-%m-%dT")
          echo "Fetching Users who committed today..."
          
          COMMITTERS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                             -H "Accept: application/vnd.github.v3+json" \
                             "https://api.github.com/repos/${{ github.repository }}/commits?since=${TODAY}00:00:00Z" | jq -r '.[].author.login' | sort -u)

          echo "Users who committed today:"
          echo "$COMMITTERS"
          echo "$COMMITTERS" > committers.txt

      - name: Find Collaborators Who Did Not Commit Today
        run: |
          echo "Finding Collaborators who did NOT commit today..."
          
          NOT_COMMITTED=$(comm -23 <(sort collaborators.txt) <(sort committers.txt))

          echo "Users who did NOT commit today:"
          echo "$NOT_COMMITTED"
          echo "$NOT_COMMITTED" > not_committed.txt

      - name: Fetch Emails of Users Who Did Not Commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching Emails of Users Who Did Not Commit Today..."
          while read -r user; do
            email=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                          -H "Accept: application/vnd.github.v3+json" \
                          "https://api.github.com/users/$user" | jq -r '.email')

            if [[ "$email" != "null" ]]; then
              echo "$user: $email"
              echo "$user: $email" >> not_committed_with_emails.txt
            else
              echo "$user: Email not available"
              echo "$user: Email not available" >> not_committed_with_emails.txt
            fi
          done < not_committed.txt
