name: List Collaborators & Notify Non-Committers

on:
  workflow_dispatch:

jobs:
  list-collaborators-and-committers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch Collaborators
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching Collaborators..."
          curl -s -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/${{ github.repository }}/collaborators" | jq -r '.[].login' > collaborators.txt

      - name: Fetch Today's Committers with Emails
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TODAY=$(date -u +"%Y-%m-%dT")
          echo "Fetching committers with emails..."
          
          curl -s -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/${{ github.repository }}/commits?since=${TODAY}00:00:00Z" | \
          jq -r '.[] | select(.commit.author.email) | "\(.author.login):\(.commit.author.email)"' | sort -u > committers_with_emails.txt

      - name: Find Collaborators Who Did Not Commit Today
        run: |
          echo "Finding Collaborators who did NOT commit today..."
          
          NOT_COMMITTED=$(comm -23 <(sort collaborators.txt) <(cut -d ':' -f1 committers_with_emails.txt))
          echo "$NOT_COMMITTED" > not_committed.txt

      - name: Auto Fetch Emails for Non-Committers
        run: |
          echo "Fetching Emails for Non-Committers..."
          
          declare -A EMAILS

          while IFS=: read -r user email; do
            EMAILS["$user"]="$email"
          done < committers_with_emails.txt

          while read -r user; do
            email="${EMAILS[$user]:-Email not available}"
            echo "$user: $email" >> not_committed_with_emails.txt
          done < not_committed.txt

      - name: Send Email Notification to Non-Committers
        env:
          SMTP_SERVER: "smtp.hostinger.com"  # Update based on your SMTP provider
          SMTP_PORT: "587"
          SMTP_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          echo "Sending Email Notifications..."
          
          while read -r line; do
            user=$(echo "$line" | cut -d ':' -f1)
            email=$(echo "$line" | cut -d ':' -f2 | xargs)

            if [[ "$email" != "Email not available" ]]; then
              echo "Sending email to $user at $email..."
              
              echo -e "Subject: Reminder: No Commit Today\nFrom: DevOps Team <noreply@yourdomain.com>\nTo: $email\n\nHi $user,\n\nWe noticed that you haven't committed to the repository today.\nPlease make sure to push your updates before the end of the day.\n\nRegards,\nDevOps Team" | \
              sendmail -S "$SMTP_SERVER" -p "$SMTP_PORT" -xu "$SMTP_USERNAME" -xp "$SMTP_PASSWORD" -f "noreply@yourdomain.com" -t "$email"

              echo "Email sent to $user ($email)"
            fi
          done < not_committed_with_emails.txt
