name: Notify Non-Committers via Hostinger SMTP

on:
  workflow_dispatch:  # Allows manual execution

jobs:
  list-collaborators-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch Collaborators
        id: collaborators
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching Collaborators..."
          COLLABORATORS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                              -H "Accept: application/vnd.github.v3+json" \
                              "https://api.github.com/repos/${{ github.repository }}/collaborators" | jq -r '.[].login')

          echo "$COLLABORATORS" > collaborators.txt

      - name: Fetch Today's Committers
        id: committers
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TODAY=$(date -u +"%Y-%m-%dT")
          COMMITTERS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                             -H "Accept: application/vnd.github.v3+json" \
                             "https://api.github.com/repos/${{ github.repository }}/commits?since=${TODAY}00:00:00Z" | jq -r '.[].author.login' | sort -u)

          echo "$COMMITTERS" > committers.txt

      - name: Find Collaborators Who Did Not Commit Today
        id: non_committers
        run: |
          NOT_COMMITTED=$(comm -23 <(sort collaborators.txt) <(sort committers.txt))
          echo "$NOT_COMMITTED" > non_committers.txt

      - name: Install and Configure msmtp
        run: |
          sudo apt-get update && sudo apt-get install -y msmtp
      
          # Ensure secrets are trimmed properly
          EMAIL_USER=$(echo -n "${{ secrets.EMAIL_USERNAME }}" | tr -d '\r' | tr -d '\n')
          EMAIL_PASS=$(echo -n "${{ secrets.EMAIL_PASSWORD }}" | tr -d '\r' | tr -d '\n')
      
          echo "Creating msmtp config file..."
          cat > ~/.msmtprc <<EOF
            defaults
            auth           on
            tls            on
            tls_starttls   off
            tls_trust_file /etc/ssl/certs/ca-certificates.crt
            logfile        ~/.msmtp.log
            
            account hostinger
            host smtp.hostinger.com
            port 465
            user $EMAIL_USER
            password $EMAIL_PASS
            from $EMAIL_USER
            
            account default : hostinger
            EOF

          chmod 600 ~/.msmtprc
      
          echo "Checking msmtp configuration..."
          cat -A ~/.msmtprc  # Debug: Show hidden characters



      - name: Send Email to Non-Committers
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        run: |
          while IFS= read -r user; do
            EMAIL_TO="pratham.chatke@thedatatechlabs.com"  # Update this based on actual emails
            echo "Sending email to $EMAIL_TO..."
            echo -e "Subject: Reminder - No Commit Today!\n\nHello ${user},\n\nYou haven't committed to the repository today. Please make sure to contribute.\n\nBest,\nDevOps Team" | msmtp "$EMAIL_TO"
          done < non_committers.txt

      - name: Send Summary Email to Admin
        env:
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: |
          NON_COMMITTED_LIST=$(cat non_committers.txt | tr '\n' ', ')
          echo -e "Subject: Daily Commit Report\n\nThe following users did not commit today:\n$NON_COMMITTED_LIST" | msmtp "$RECIPIENT_EMAIL"
