name: Notify Non-Committers via Hostinger SMTP

on:
  workflow_dispatch:  # Allows manual execution

jobs:
  list-collaborators-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch Collaborators
        id: collaborators
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching Collaborators..."
          COLLABORATORS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                              -H "Accept: application/vnd.github.v3+json" \
                              "https://api.github.com/repos/${{ github.repository }}/collaborators" | jq -r '.[].login')

          echo "All Collaborators:"
          echo "$COLLABORATORS"
          echo "$COLLABORATORS" > collaborators.txt

      - name: Fetch Today's Committers
        id: committers
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TODAY=$(date -u +"%Y-%m-%dT")
          echo "Fetching Users who committed today..."

          COMMITTERS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                             -H "Accept: application/vnd.github.v3+json" \
                             "https://api.github.com/repos/${{ github.repository }}/commits?since=${TODAY}00:00:00Z" | jq -r '.[].author.login' | sort -u)

          echo "Users who committed today:"
          echo "$COMMITTERS"
          echo "$COMMITTERS" > committers.txt

      - name: Find Collaborators Who Did Not Commit Today
        id: non_committers
        run: |
          echo "Finding Collaborators who did NOT commit today..."
          
          NOT_COMMITTED=$(comm -23 <(sort collaborators.txt) <(sort committers.txt))

          echo "Users who did NOT commit today:"
          echo "$NOT_COMMITTED"
          echo "$NOT_COMMITTED" > non_committers.txt

      - name: Install and Configure msmtp
        run: |
          sudo apt-get update && sudo apt-get install -y msmtp
          
          echo "Creating msmtp config file..."
          cat <<EOF > ~/.msmtprc
          defaults
          auth on
          tls on
          tls_trust_file /etc/ssl/certs/ca-certificates.crt
          logfile ~/.msmtp.log

          account hostinger
          host smtp.hostinger.com
          port 587
          user "${{ secrets.EMAIL_USERNAME }}"
          password "${{ secrets.EMAIL_PASSWORD }}"
          from "${{ secrets.EMAIL_USERNAME }}"
          auth on
          tls on

          account default : hostinger
          EOF

          chmod 600 ~/.msmtprc

      - name: Debug Email Variables
        run: |
          echo "Debug: EMAIL_USERNAME='${{ secrets.EMAIL_USERNAME }}'"
          echo "Debug: RECIPIENT_EMAIL='${{ secrets.RECIPIENT_EMAIL }}'"

      - name: Map GitHub Usernames to Emails
        run: |
          declare -A USER_EMAILS
          USER_EMAILS["Pratham-TDTL"]="pratham.chatke@thedatatechlabs.com"

          while IFS= read -r user; do
            EMAIL_TO="${USER_EMAILS[$user]}"
            if [[ -n "$EMAIL_TO" ]]; then
              echo "DEBUG: Sending email to $EMAIL_TO..."
              echo -e "Subject: Reminder - No Commit Today!\n\nHello ${user},\n\nYou haven't committed to the repository today. Please make sure to contribute.\n\nBest,\nDevOps Team" | msmtp \
                --from="${{ secrets.EMAIL_USERNAME }}" \
                --host=smtp.hostinger.com --port=587 --auth=on --tls=on \
                --user="${{ secrets.EMAIL_USERNAME }}" \
                --passwordeval "echo '${{ secrets.EMAIL_PASSWORD }}'" \
                "$EMAIL_TO"
            else
              echo "Skipping: No email found for $user"
            fi
          done < non_committers.txt

      - name: Send Summary Email to Admin
        run: |
          NON_COMMITTED_LIST=$(cat non_committers.txt | tr '\n' ', ')
          echo "Sending summary email to admin..."
          echo -e "Subject: Daily Commit Report\n\nThe following users did not commit today:\n$NON_COMMITTED_LIST" | msmtp \
            --from="${{ secrets.EMAIL_USERNAME }}" \
            --host=smtp.hostinger.com --port=587 --auth=on --tls=on \
            --user="${{ secrets.EMAIL_USERNAME }}" \
            --passwordeval "echo '${{ secrets.EMAIL_PASSWORD }}'" \
            "${{ secrets.RECIPIENT_EMAIL }}"
