name: Notify Non-Committers via Hostinger SMTP

on:
  workflow_dispatch:  # Allows manual execution

jobs:
  list-collaborators-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch Collaborators
        id: collaborators
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching Collaborators..."
          COLLABORATORS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                              -H "Accept: application/vnd.github.v3+json" \
                              "https://api.github.com/repos/${{ github.repository }}/collaborators" | jq -r '.[].login')
          echo "$COLLABORATORS" > collaborators.txt

      - name: Fetch Today's Committers
        id: committers
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TODAY=$(date -u +"%Y-%m-%dT")
          COMMITTERS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                             -H "Accept: application/vnd.github.v3+json" \
                             "https://api.github.com/repos/${{ github.repository }}/commits?since=${TODAY}00:00:00Z" | jq -r '.[].author.login' | sort -u)
          echo "$COMMITTERS" > committers.txt

      - name: Find Non-Committers
        id: non_committers
        run: |
          comm -23 <(sort collaborators.txt) <(sort committers.txt) > non_committers.txt
          echo "Non-committers today:"
          cat non_committers.txt

      - name: Install and Configure msmtp
        run: |
          sudo apt-get update && sudo apt-get install -y msmtp
          cat <<EOF > ~/.msmtprc
          defaults
          auth           login
          tls            on
          tls_trust_file /etc/ssl/certs/ca-certificates.crt
          logfile        ~/.msmtp.log
          account hostinger
          host smtp.hostinger.com
          port 465
          user "${{ secrets.EMAIL_USERNAME }}"
          password "${{ secrets.EMAIL_PASSWORD }}"
          from "${{ secrets.EMAIL_USERNAME }}"
          auth login
          tls on
          account default : hostinger
          EOF
          chmod 600 ~/.msmtprc

      - name: Send Emails to Non-Committers
        run: |
          while IFS= read -r user; do
            EMAIL_TO=$(grep "^$user=" emails.txt | cut -d'=' -f2)
            if [ -n "$EMAIL_TO" ]; then
              echo "Sending email to $EMAIL_TO..."
              echo -e "Subject: Reminder - No Commit Today!\n\nHello $user,\n\nYou haven't committed today. Please contribute.\n\nBest,\nDevOps Team" | msmtp --from="${{ secrets.EMAIL_USERNAME }}" --host=smtp.hostinger.com --port=587 --auth=on --tls=on --user="${{ secrets.EMAIL_USERNAME }}" --passwordeval "echo ${{ secrets.EMAIL_PASSWORD }}" "$EMAIL_TO"
            else
              echo "No email found for $user. Skipping..."
            fi
          done < non_committers.txt

      - name: Send Summary to Admin
        run: |
          NON_COMMITTED_LIST=$(cat non_committers.txt | tr '\n' ', ')
          echo -e "Subject: Daily Commit Report\n\nUsers who did not commit today:\n$NON_COMMITTED_LIST" | msmtp --from="${{ secrets.EMAIL_USERNAME }}" --host=smtp.hostinger.com --port=587 --auth=on --tls=on --user="${{ secrets.EMAIL_USERNAME }}" --passwordeval "echo ${{ secrets.EMAIL_PASSWORD }}" "${{ secrets.RECIPIENT_EMAIL }}"
