name: List Collaborators & Notify Non-Committers

on:
  workflow_dispatch:  # Allows manual execution

jobs:
  list-collaborators-and-committers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch Collaborators
        id: collaborators
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching Collaborators..."
          curl -s -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/${{ github.repository }}/collaborators" | jq -r '.[].login' | sort -u > collaborators.txt

          echo "All Collaborators:"
          cat collaborators.txt

      - name: Fetch Today's Committers
        id: committers
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TODAY=$(date -u +"%Y-%m-%dT")
          echo "Fetching Users who committed today..."
          
          curl -s -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/${{ github.repository }}/commits?since=${TODAY}00:00:00Z" | jq -r '.[].author.login' | sort -u > committers.txt

          echo "Users who committed today:"
          cat committers.txt

      - name: Find Collaborators Who Did Not Commit Today
        run: |
          echo "Finding Collaborators who did NOT commit today..."
          comm -23 <(sort collaborators.txt | uniq) <(sort committers.txt | uniq) > not_committed.txt

          echo "Users who did NOT commit today:"
          cat not_committed.txt

      - name: Fetch Emails of Non-Committers
        run: |
          echo "Fetching Emails of Non-Committers..."
          declare -A EMAILS

          EMAILS["Yogesh-TDTL"]="yogesh.more@thedatatechlabs.com"
          EMAILS["Pratham-TDTL"]="pratham.chatke@thedatatechlabs.com"

          while read -r user; do
            email="${EMAILS[$user]:-}"
            if [[ -n "$email" ]]; then
              echo "$user: $email" >> not_committed_with_emails.txt
            else
              echo "Skipping $user: No email available"
            fi
          done < not_committed.txt

          echo "Final list of users with emails:"
          cat not_committed_with_emails.txt || echo "No users to notify."

      - name: Install ssmtp
        run: |
          sudo apt-get update
          sudo apt-get install -y ssmtp

      - name: Configure ssmtp
        run: |
          echo "Setting up ssmtp configuration..."
          sudo bash -c "cat > /etc/ssmtp/ssmtp.conf <<EOF
          root=${{ secrets.EMAIL_USERNAME }}
          mailhub=smtp.hostinger.com:587
          AuthUser=${{ secrets.EMAIL_USERNAME }}
          AuthPass=${{ secrets.EMAIL_PASSWORD }}
          UseTLS=YES
          UseSTARTTLS=YES
          EOF"

          sudo chmod 600 /etc/ssmtp/ssmtp.conf


      - name: Debug Email Formatting
        run: |
          echo "Checking email format before sending..."
          while IFS=: read -r user email; do
            email=$(echo "$email" | tr -d '[:space:]' | tr -d '\r')
            echo "User: '$user' | Email: '$email'"
          done < not_committed_with_emails.txt

      - name: Send Email Notification to Non-Committers
        run: |
          echo "Sending Email Notifications..."

          while IFS=: read -r user email; do
            email=$(echo "$email" | tr -d '[:space:]' | tr -d '\r')

            if [[ -z "$email" ]]; then
              echo "Skipping $user: No email found."
              continue
            fi
            
            if [[ ! "$email" =~ ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]]; then
              echo "Skipping $user: Invalid email format - '$email'"
              continue
            fi

            echo "Processing: User='$user' | Email='$email'"
            echo -e "Subject: Reminder: No Commit Today\nFrom: DevOps Team <${{ secrets.EMAIL_USERNAME }}>\nTo: $email\n\nHi $user,\n\nWe noticed that you haven't committed to the repository today.\nPlease push your updates before the end of the day.\n\nRegards,\nDevOps Team" > email.txt

            echo "Sending email using ssmtp..."
            ssmtp "$email" < email.txt

            echo "Email sent to $user ($email)"
          done < not_committed_with_emails.txt
