name: Check Daily Contributions

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual execution

jobs:
  check-contributions:
    runs-on: ubuntu-latest

    steps:
      - name: Get Repository Collaborators
        id: get_collaborators
        run: |
          COLLABORATORS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/collaborators" | jq -r '.[].login')

          echo "COLLABORATORS<<EOF" >> $GITHUB_ENV
          echo "$COLLABORATORS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Check Daily Contributions
        id: check_contributions
        run: |
          last_24_hours=$(date -u -d '1 day ago' +%Y-%m-%dT%H:%M:%SZ)
          active_collaborators=()
          inactive_collaborators=()

          while IFS= read -r user; do
            commits=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/commits?author=$user&since=$last_24_hours")

            if [[ "$commits" == "[]" ]]; then
              inactive_collaborators+=("$user")
            else
              active_collaborators+=("$user")
            fi
          done <<< "${{ env.COLLABORATORS }}"

          echo -e "✅ Active Collaborators (Pushed Today):\n${active_collaborators[@]}"
          echo -e "❌ Inactive Collaborators (Did NOT Push Today):\n${inactive_collaborators[@]}"

          echo "INACTIVE_COLLABORATORS<<EOF" >> $GITHUB_ENV
          printf "%s\n" "${inactive_collaborators[@]}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Send Email to Inactive Collaborators
        if: env.INACTIVE_COLLABORATORS != ''
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Daily Reminder: You Haven't Pushed Code!"
          body: |
            The following collaborators have not pushed any commits in the last 24 hours:
            
            ${{ env.INACTIVE_COLLABORATORS }}

            Please ensure you push your updates regularly.
          to: ${{ secrets.RECIPIENT_EMAIL }}
          from: GitHub Actions
