name: List Collaborators & Notify Non-Committers

on:
  workflow_dispatch:  # Allows manual execution

jobs:
  list-collaborators-and-committers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch Collaborators
        id: collaborators
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching Collaborators..."
          COLLABORATORS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                              -H "Accept: application/vnd.github.v3+json" \
                              "https://api.github.com/repos/${{ github.repository }}/collaborators" | jq -r '.[].login')

          echo "All Collaborators:"
          echo "$COLLABORATORS"
          echo "$COLLABORATORS" > collaborators.txt

      - name: Fetch Today's Committers
        id: committers
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TODAY=$(date -u +"%Y-%m-%dT")
          echo "Fetching Users who committed today..."
          
          COMMITTERS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                             -H "Accept: application/vnd.github.v3+json" \
                             "https://api.github.com/repos/${{ github.repository }}/commits?since=${TODAY}00:00:00Z" | jq -r '.[].author.login' | sort -u)

          echo "Users who committed today:"
          echo "$COMMITTERS"
          echo "$COMMITTERS" > committers.txt

      - name: Find Collaborators Who Did Not Commit Today
        run: |
          echo "Finding Collaborators who did NOT commit today..."
          
          NOT_COMMITTED=$(comm -23 <(sort collaborators.txt) <(sort committers.txt))

          echo "Users who did NOT commit today:"
          echo "$NOT_COMMITTED"
          echo "$NOT_COMMITTED" > not_committed.txt

      - name: Fetch Emails of Non-Committers
        run: |
          echo "Fetching Emails of Non-Committers..."
          declare -A EMAILS

          # Manually define known emails (replace with real emails)
          EMAILS["Yogesh-TDTL"]="yogesh.more@thedatatechlabs.com"
          EMAILS["Pratham-TDTL"]="pratham.chatke@thedatatechlabs.com"

          while read -r user; do
            email="${EMAILS[$user]:-Email not available}"
            echo "$user: $email"
            echo "$user: $email" >> not_committed_with_emails.txt
          done < not_committed.txt
      - name: Install msmtp
        run: |
          sudo apt-get update
          sudo apt-get install -y msmtp msmtp-mta

      - name: Configure msmtp
        run: |
          echo "Setting up msmtp configuration..."
          cat <<EOF > ~/.msmtprc
          defaults
          auth           on
          tls            on
          tls_trust_file /etc/ssl/certs/ca-certificates.crt
          logfile        ~/.msmtp.log

          account hostinger
          host smtp.hostinger.com
          port 587
          from ${{ secrets.EMAIL_USERNAME }}
          user ${{ secrets.EMAIL_USERNAME }}
          password ${{ secrets.EMAIL_PASSWORD }}

          account default : hostinger
          EOF

          chmod 600 ~/.msmtprc

      - name: Send Email Notification to Non-Committers
        run: |
          echo "Sending Email Notifications..."

          while read -r line; do
            user=$(echo "$line" | cut -d ':' -f1)
            email=$(echo "$line" | cut -d ':' -f2 | xargs)

            if [[ "$email" != "Email not available" ]]; then
              echo "Sending email to $user at $email..."
              
              echo -e "Subject: Reminder: No Commit Today\nFrom: DevOps Team <${{ secrets.EMAIL_USERNAME }}>\nTo: $email\n\nHi $user,\n\nWe noticed that you haven't committed to the repository today.\nPlease make sure to push your updates before the end of the day.\n\nRegards,\nDevOps Team" | \
              msmtp --debug --from=${{ secrets.EMAIL_USERNAME }} -t "$email"

              echo "Email sent to $user ($email)"
            fi
          done < not_committed_with_emails.txt

