name: Notify Non-Committers via Hostinger SMTP

on:
  workflow_dispatch:  # Allows manual execution

jobs:
  list-collaborators-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt update && sudo apt install -y gh
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Fetch Collaborators
        run: |
          echo "Fetching Collaborators..."
          gh api repos/${{ github.repository }}/collaborators --paginate --jq '.[].login' > collaborators.txt
          echo "Collaborators fetched successfully."

      - name: Fetch Today's Committers
        run: |
          TODAY=$(date -u +"%Y-%m-%dT")
          echo "Fetching Users who committed today..."
          gh api repos/${{ github.repository }}/commits?since=${TODAY}00:00:00Z --paginate --jq '.[].author.login' | sort -u > committers.txt
          echo "Committers fetched successfully."

      - name: Find Non-Committers
        run: |
          echo "Finding Collaborators who did NOT commit today..."
          comm -23 <(sort collaborators.txt) <(sort committers.txt) > non_committers.txt
          echo "Non-Committers Identified."

      - name: Fetch Emails of Non-Committers
        run: |
          > user_emails.txt
          while IFS= read -r user; do
            echo "Fetching email for $user..."
            
            # Attempt to fetch email using GitHub CLI
            EMAIL=$(gh api users/$user --jq '.email' || echo "")

            # Fallback if email is null or empty
            if [ "$EMAIL" == "null" ] || [ -z "$EMAIL" ]; then
              EMAIL="${user}@users.noreply.github.com"
            fi

            echo "$user=$EMAIL" >> user_emails.txt
            echo "Fetched email for $user: $EMAIL"
          done < non_committers.txt

      - name: Install and Configure msmtp
        run: |
          sudo apt-get update && sudo apt-get install -y msmtp
          
          echo "Creating msmtp config file..."
          cat <<EOF > ~/.msmtprc
          defaults
          auth           login
          tls            on
          tls_trust_file /etc/ssl/certs/ca-certificates.crt
          logfile        ~/.msmtp.log
          account hostinger
          host smtp.hostinger.com
          port 587  # Port 587 is recommended for TLS
          user "${{ secrets.EMAIL_USERNAME }}"
          password "${{ secrets.EMAIL_PASSWORD }}"
          from "${{ secrets.EMAIL_USERNAME }}"
          auth login
          tls on
          account default : hostinger
          EOF
          chmod 600 ~/.msmtprc


      - name: View msmtp logs
        run: |
          cat ~/.msmtp.log

      - name: Send Email to Non-Committers
        run: |
          while IFS= read -r user; do
            EMAIL_TO=$(grep "^$user=" user_emails.txt | cut -d '=' -f 2)

            if [[ -n "$EMAIL_TO" ]]; then
              echo "Sending email to $EMAIL_TO..."
              echo -e "Subject: Reminder - No Commit Today!\n\nHello ${user},\n\nYou haven't committed to the repository today. Please make sure to contribute.\n\nBest,\nDevOps Team" | msmtp --from="${{ secrets.EMAIL_USERNAME }}" --host=smtp.hostinger.com --port=587 --auth=on --tls=on --user="${{ secrets.EMAIL_USERNAME }}" --passwordeval "echo ${{ secrets.EMAIL_PASSWORD }}" "$EMAIL_TO"
            else
              echo "No email found for $user, skipping..."
            fi
          done < non_committers.txt

      - name: Send Summary Email to Admin
        run: |
          NON_COMMITTED_LIST=$(cat non_committers.txt | tr '\n' ', ')
          echo -e "Subject: Daily Commit Report\n\nThe following users did not commit today:\n$NON_COMMITTED_LIST" | msmtp --from="${{ secrets.EMAIL_USERNAME }}" --host=smtp.hostinger.com --port=587 --auth=on --tls=on --user="${{ secrets.EMAIL_USERNAME }}" --passwordeval "echo ${{ secrets.EMAIL_PASSWORD }}" "${{ secrets.RECIPIENT_EMAIL }}"
