name: Check Recent Commits

on:
  workflow_dispatch:
  schedule:
    - cron: "30 13 * * 1-5"  # Runs at 7 PM IST (1:30 PM UTC) Monday to Friday
    - cron: "30 3 * * 1-5"  # Runs at 9 AM IST (3:30 AM UTC) Monday to Friday

jobs:
  check-recent-committers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Check Recent Commit Activity
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NON_COMMITTED_USER: "Yogesh-TDTL"
        run: |
          # Get current and past timestamps
          CURRENT_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          SINCE_TIME=$(date -u -d '24 hours ago' +"%Y-%m-%dT%H:%M:%SZ")
          
          # Fetch commits
          API_URL="https://api.github.com/repos/${{ github.repository }}/commits?author=$NON_COMMITTED_USER&since=$SINCE_TIME"
          echo "Checking commits from: $SINCE_TIME to $CURRENT_TIME"
          echo "API URL: $API_URL"
          RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" "$API_URL")
          
          # Debug API response
          echo "API Response: $RESPONSE"
          
          # Count commits
          COMMIT_COUNT=$(echo "$RESPONSE" | jq length)
          
          echo "Number of commits found: $COMMIT_COUNT"
          
          if [ "$COMMIT_COUNT" -eq 0 ]; then
            echo "No commits found in the last 24 hours."
          else
            echo "Developer has committed within the last 24 hours."
          fi
