name: Test Email Notifications

on:
  workflow_dispatch:  # Allows manual execution

jobs:
  list-collaborators-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch Collaborators
        id: collaborators
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching Collaborators..."
          COLLABORATORS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                              -H "Accept: application/vnd.github.v3+json" \
                              "https://api.github.com/repos/${{ github.repository }}/collaborators" | jq -r '.[].login')
          echo "All Collaborators:"
          echo "$COLLABORATORS"
          echo "$COLLABORATORS" > collaborators.txt

      - name: Find Collaborators Who Did Not Commit Today
        id: non_committers
        run: |
          echo "Finding Collaborators who did NOT commit today..."
          NOT_COMMITTED=$(comm -23 <(sort collaborators.txt) <(sort committers.txt))
          echo "Users who did NOT commit today:"
          echo "$NOT_COMMITTED"
          echo "$NOT_COMMITTED" > non_committers.txt

      - name: Install and Configure msmtp
        run: |
          sudo apt-get update && sudo apt-get install -y msmtp
          
          echo "Creating msmtp config file..."
          cat <<EOF > ~/.msmtprc
          defaults
          auth           login
          tls            on
          tls_trust_file /etc/ssl/certs/ca-certificates.crt
          logfile        ~/.msmtp.log
          account hostinger
          host smtp.hostinger.com
          port 465
          user "${{ secrets.EMAIL_USERNAME }}"
          password "${{ secrets.EMAIL_PASSWORD }}"
          from "${{ secrets.EMAIL_USERNAME }}"
          account default : hostinger
          EOF
          chmod 600 ~/.msmtprc

      - name: Send 7 PM Reminder to Non-Committers (Test)
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        run: |
          while IFS= read -r user; do
            EMAIL_TO="yogesh.more@thedatatechlabs.com"  
            printf "From: $EMAIL_USERNAME\nTo: $EMAIL_TO\nSubject: Reminder - No Commit Today!\n\nHello ${user},\n\nThis is a reminder that as of now, no commit has been recorded from your end in the repository today. Please ensure that you push your updates before the end of the day to stay aligned with our workflow.\nIf there’s any issue preventing you from committing, let me know immediately.\nLooking forward to your update.\n\nBest,\nCloud Team" | msmtp --from=$EMAIL_USERNAME --host=smtp.hostinger.com --port=587 --auth=on --tls=on --user=$EMAIL_USERNAME --passwordeval "echo ${{ secrets.EMAIL_PASSWORD }}" "$EMAIL_TO"
          done < non_committers.txt

      - name: Send Next Morning Follow-up to Non-Committers (Test)
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        run: |
          while IFS= read -r user; do
            EMAIL_TO="yogesh.more@thedatatechlabs.com"  
            echo -e "From: $EMAIL_USERNAME\nTo: $EMAIL_TO\nSubject: Warning - No Commit Yesterday!\n\nHello ${user},\n\nI have reviewed today's repository activity and noticed that you have not committed any updates. This is unacceptable and goes against our workflow expectations. Immediate action is required—ensure your contributions are updated without further delay.\nLet me know if there is any issue preventing you from completing your work. I expect this to be resolved promptly. \nFailure to comply may lead to further action.\n\nRegards,\nCloud Team" | msmtp --from=$EMAIL_USERNAME --host=smtp.hostinger.com --port=587 --auth=on --tls=on --user=$EMAIL_USERNAME --passwordeval "echo ${{ secrets.EMAIL_PASSWORD }}" "$EMAIL_TO"
          done < non_committers.txt

      - name: Send Summary Email to Admins (Test)
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        run: |
          export LANG=en_US.UTF-8
          export LC_ALL=en_US.UTF-8
          RECIPIENT_EMAIL="yogesh.more@thedatatechlabs.com"
          NON_COMMITTED_LIST=$(cat non_committers.txt | tr '\n' ', ' | iconv -f UTF-8 -t UTF-8)
          printf "From: $EMAIL_USERNAME\nTo: $RECIPIENT_EMAIL\nSubject: ⚠️ Daily Commit Report - Non-Committers Alert\n\nHello Team,\n\nDespite the reminder sent yesterday, the following users have not committed any updates to the repository:\n\n$NON_COMMITTED_LIST\n\nThis is a breach of our workflow requirements. I have sent a follow-up email instructing immediate action.\n\nPlease advise on the next steps if no action is taken.\n\nBest Regards,\nCloud Team" | iconv -f UTF-8 -t UTF-8 | msmtp --from=$EMAIL_USERNAME --host=smtp.hostinger.com --port=587 --auth=on --tls=on --user=$EMAIL_USERNAME --passwordeval "echo ${{ secrets.EMAIL_PASSWORD }}" "$RECIPIENT_EMAIL"
