name: Check Recent Committers and Notify Non-Committers

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:  # Allows manual triggering

jobs:
  check-recent-committers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Install and Configure msmtp
        run: |
          sudo apt-get update && sudo apt-get install -y msmtp
          cat <<EOF > ~/.msmtprc
          defaults
          auth           login
          tls            on
          tls_trust_file /etc/ssl/certs/ca-certificates.crt
          logfile        ~/.msmtp.log
          account hostinger
          host smtp.hostinger.com
          port 465
          user "${{ secrets.EMAIL_USERNAME }}"
          password "${{ secrets.EMAIL_PASSWORD }}"
          from "${{ secrets.EMAIL_USERNAME }}"
          account default : hostinger
          EOF
          chmod 600 ~/.msmtprc
      
      - name: List Collaborators and Check Recent Commit Activity
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MANAGER_USERNAME: "Yogesh-TDTL"  # Replace with actual manager's GitHub username
        run: |
          echo "Fetching Collaborators..."
          COLLABORATORS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/${{ github.repository }}/collaborators" \
               | jq -r '.[].login')
          
          echo "Collaborators List:"
          echo "$COLLABORATORS"
          
          echo "\nRecent Committers (Last Hour):"
          COMMITTED=false
          NON_COMMITTED_USERS=""
          
          for user in $COLLABORATORS; do
            if [ "$user" = "$MANAGER_USERNAME" ]; then
              continue  # Skip manager
            fi
            
            echo "Checking commits for: $user"
            RECENT_COMMITS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                 -H "Accept: application/vnd.github.v3+json" \
                 "https://api.github.com/repos/${{ github.repository }}/commits?author=$user&since=$(date -u -d '1 hour ago' +"%Y-%m-%dT%H:%M:%SZ")" \
                 | jq length)
            
            if [ "$RECENT_COMMITS" -gt 0 ]; then
              echo "$user committed in the last hour ($RECENT_COMMITS commits)"
            else
              NON_COMMITTED_USERS+="$user\n"
            fi
          done
          
          echo "\nNon-Committers (Last Hour):"
          echo -e "$NON_COMMITTED_USERS"
          
          echo "Sending Reminder Emails..."
          for user in $NON_COMMITTED_USERS; do
            email="$yogesh.more@thedatatechlabs.com"  # Replace this logic to fetch actual emails
            echo -e "Subject: Reminder to Commit\n\nHello $user,\n\nYou haven't committed in the last hour. Please make sure to contribute." | msmtp -a default "$email"
            echo "Email sent to: $email"
          done
