name: Notify Non-Committers via Mail

on:
  workflow_dispatch:
  schedule:
    - cron: "30 13 * * 1-5"  # 7:30 PM IST (13:30 UTC)
    - cron: "30 3 * * 1-5"   # 9:30 AM IST (03:30 UTC)

jobs:
  list-collaborators-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch Collaborators
        id: collaborators
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching Collaborators..."
          COLLABORATORS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                              -H "Accept: application/vnd.github.v3+json" \
                              "https://api.github.com/repos/${{ github.repository }}/collaborators" | jq -r '.[].login')

          echo "$COLLABORATORS" | tr '[:upper:]' '[:lower:]' > collaborators.txt

          # Define managers to exclude
          MANAGERS=("imrantdtl")  # Replace with actual usernames (lowercase)

          # Remove managers from collaborators
          grep -vxF -f <(printf "%s\n" "${MANAGERS[@]}") collaborators.txt > temp.txt && mv temp.txt collaborators.txt

      - name: Fetch Last 24 Hours Committers
        id: committers
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          YESTERDAY=$(date -u -d "1 day ago" +"%Y-%m-%dT")
          echo "Fetching Users who committed in the last 24 hours..."

          PAGE=1
          COMMITTERS=""
          while :; do
            RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                -H "Accept: application/vnd.github.v3+json" \
                "https://api.github.com/repos/${{ github.repository }}/commits?since=${YESTERDAY}00:00:00Z&page=${PAGE}&per_page=100")
            
            PAGE_COMMITTERS=$(echo "$RESPONSE" | jq -r '.[].author.login // .[].commit.author.name' | sort -u)

            [ -z "$PAGE_COMMITTERS" ] && break

            COMMITTERS+=$'\n'"$PAGE_COMMITTERS"
            PAGE=$((PAGE + 1))
          done

          echo "$COMMITTERS" | tr '[:upper:]' '[:lower:]' > committers.txt

      - name: Find Non-Committers
        id: non_committers
        run: |
          comm -23 <(sort collaborators.txt) <(sort committers.txt) > non_committers.txt
          echo "Non-committers list generated: $(cat non_committers.txt)"

      - name: Install and Configure msmtp
        run: |
          sudo apt-get update && sudo apt-get install -y msmtp
          cat <<EOF > ~/.msmtprc
          defaults
          auth           login
          tls            on
          tls_trust_file /etc/ssl/certs/ca-certificates.crt
          logfile        ~/.msmtp.log
          account hostinger
          host smtp.hostinger.com
          port 587
          user "${{ secrets.EMAIL_USERNAME }}"
          password "${{ secrets.EMAIL_PASSWORD }}"
          from "${{ secrets.EMAIL_USERNAME }}"
          account default : hostinger
          EOF
          chmod 600 ~/.msmtprc

      - name: Send 7 PM Reminder to Non-Committers
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        run: |
          export LANG=en_US.UTF-8
          export LC_ALL=en_US.UTF-8
          while IFS= read -r user; do
            EMAIL_TO="yogesh.more@thedatatechlabs.com"
            printf "From: $EMAIL_USERNAME\nTo: $EMAIL_TO\nSubject: ⚠️ Reminder - No Commit Today!\nMIME-Version: 1.0\nContent-Type: text/plain; charset=UTF-8\nContent-Transfer-Encoding: 8bit\n\nHello ${user},\n\nThis is a reminder that as of now, no commit has been recorded from your end in the repository today. Please ensure that you push your updates before the end of the day to stay aligned with our workflow.\n\nIf there’s any issue preventing you from committing, let me know immediately.\n\nLooking forward to your update.\n\nBest,\nCloud Team" | msmtp --from=$EMAIL_USERNAME --host=smtp.hostinger.com --port=587 --auth=on --tls=on --user=$EMAIL_USERNAME --passwordeval "echo ${{ secrets.EMAIL_PASSWORD }}" "$EMAIL_TO"
          done < non_committers.txt

      - name: Send Next Morning Follow-up to Non-Committers
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        run: |
          export LANG=en_US.UTF-8
          export LC_ALL=en_US.UTF-8
          while IFS= read -r user; do
            EMAIL_TO="yogesh.more@thedatatechlabs.com"
            printf "From: $EMAIL_USERNAME\nTo: $EMAIL_TO\nSubject: 🚨 Warning - No Commit Yesterday!\nMIME-Version: 1.0\nContent-Type: text/plain; charset=UTF-8\nContent-Transfer-Encoding: 8bit\n\nHello ${user},\n\nI have reviewed today's repository activity and noticed that you have not committed any updates. This is unacceptable and goes against our workflow expectations.\n\nImmediate action is required—ensure your contributions are updated without further delay.\n\nLet me know if there is any issue preventing you from completing your work. I expect this to be resolved promptly.\n\nFailure to comply may lead to further action.\n\nRegards,\nCloud Team" | msmtp --from=$EMAIL_USERNAME --host=smtp.hostinger.com --port=587 --auth=on --tls=on --user=$EMAIL_USERNAME --passwordeval "echo ${{ secrets.EMAIL_PASSWORD }}" "$EMAIL_TO"
          done < non_committers.txt

      - name: Send Summary Email to Admins
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        run: |
          export LANG=en_US.UTF-8
          export LC_ALL=en_US.UTF-8
          RECIPIENT_EMAIL="yogesh.more@thedatatechlabs.com"

          NON_COMMITTED_LIST=$(cat non_committers.txt | tr '\n' ', ' | iconv -f UTF-8 -t UTF-8//IGNORE)

          printf "From: $EMAIL_USERNAME\nTo: $RECIPIENT_EMAIL\nSubject: Daily Commit Report - Non-Committers Alert\nMIME-Version: 1.0\nContent-Type: text/plain; charset=UTF-8\nContent-Transfer-Encoding: 8bit\n\nHello Team,\n\nDespite the reminder sent yesterday, the following users have not committed any updates to the repository:\n\n$NON_COMMITTED_LIST\n\nThis is a breach of our workflow requirements. I have sent a follow-up email instructing immediate action.\n\nPlease advise on the next steps if no action is taken.\n\nBest Regards,\nCloud Team" | msmtp --from=$EMAIL_USERNAME --host=smtp.hostinger.com --port=587 --auth=on --tls=on --user=$EMAIL_USERNAME --passwordeval "echo ${{ secrets.EMAIL_PASSWORD }}" "$RECIPIENT_EMAIL"
