name: Notify Non-Committers via Mail
on:
  workflow_dispatch:
  schedule:
    - cron: "30 13 * * 1-5"  # 7:30 PM IST (13:30 UTC) - Reminder Email
    - cron: "30 3 * * 1-5"   # 9:30 AM IST (03:30 UTC) - Warning Email & Report 

jobs:
  list-collaborators-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch Collaborators
        id: collaborators
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching Collaborators..."
          COLLABORATORS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                              -H "Accept: application/vnd.github.v3+json" \
                              "https://api.github.com/repos/${{ github.repository }}/collaborators" | jq -r '.[].login')
          
          echo "$COLLABORATORS" > collaborators.txt
          
          # Define managers to exclude
          MANAGERS=("ImranTDTL")  # Replace with actual usernames
          grep -vxF -f <(printf "%s\n" "${MANAGERS[@]}") collaborators.txt > temp.txt && mv temp.txt collaborators.txt
          
      - name: Fetch Committers Before 7 PM
        id: committers_7pm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TODAY=$(date -u +"%Y-%m-%dT00:00:00Z")
          SEVEN_PM_UTC=$(date -u +"%Y-%m-%dT13:30:00Z")  # 7:30 PM IST in UTC
          
          echo "Fetching users who committed from $TODAY until $SEVEN_PM_UTC..."
          
          COMMITTERS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                             -H "Accept: application/vnd.github.v3+json" \
                             "https://api.github.com/repos/${{ github.repository }}/commits?since=$TODAY&until=$SEVEN_PM_UTC" | jq -r '.[] | select(.author != null) | .author.login' | sort -u)
          
          echo "$COMMITTERS" > committers_7pm.txt
          
      - name: Find Non-Committers Before 7 PM
        id: non_committers_7pm
        run: |
          awk 'NF' collaborators.txt | sort -u > collaborators_clean.txt
          awk 'NF' committers_7pm.txt | sort -u > committers_clean.txt
          comm -23 collaborators_clean.txt committers_clean.txt > non_committers_7pm.txt

      - name: Fetch Committers After 7 PM (For Next Day 9 AM Warning)
        if: github.event.schedule == '30 3 * * 1-5'
        id: committers_after_7pm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          SEVEN_PM_UTC=$(date -u +"%Y-%m-%dT13:30:00Z")
          NOW_UTC=$(date -u +"%Y-%m-%dT03:30:00Z")  # 9:30 AM IST in UTC
          
          echo "Fetching users who committed from $SEVEN_PM_UTC until $NOW_UTC..."
          
          COMMITTERS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                             -H "Accept: application/vnd.github.v3+json" \
                             "https://api.github.com/repos/${{ github.repository }}/commits?since=$SEVEN_PM_UTC&until=$NOW_UTC" | jq -r '.[] | select(.author != null) | .author.login' | sort -u)
          
          echo "$COMMITTERS" > committers_after_7pm.txt

      - name: Find Still Non-Committers After 7 PM (For 9 AM Email & Report)
        if: github.event.schedule == '30 3 * * 1-5'
        id: final_non_committers
        run: |
          awk 'NF' committers_after_7pm.txt | sort -u > committers_after_7pm_clean.txt
          comm -23 non_committers_7pm.txt committers_after_7pm_clean.txt > final_non_committers.txt

      - name: Install and Configure msmtp
        run: |
          sudo apt-get update && sudo apt-get install -y msmtp
          cat <<EOF > ~/.msmtprc
          defaults
          auth           login
          tls            on
          tls_trust_file /etc/ssl/certs/ca-certificates.crt
          logfile        ~/.msmtp.log
          account hostinger
          host smtp.hostinger.com
          port 465
          user "${{ secrets.EMAIL_USERNAME }}"
          password "${{ secrets.EMAIL_PASSWORD }}"
          from "${{ secrets.EMAIL_USERNAME }}"
          account default : hostinger
          EOF
          chmod 600 ~/.msmtprc

      - name: Send 7 PM Reminder to Non-Committers
        if: github.event.schedule == '30 13 * * 1-5' && success() && hashFiles('non_committers_7pm.txt') != ''
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        run: |
          export LANG=en_US.UTF-8
          export LC_ALL=en_US.UTF-8
          while IFS= read -r user; do
            EMAIL_TO="yogesh.more@thedatatechlabs.com"
            printf "From: $EMAIL_USERNAME\nTo: $EMAIL_TO\nSubject: ⚠️ Reminder - No Commit Today!\n\nHello ${user},\n\nYou haven't committed anything today. Please push your updates before the end of the day.\n\nBest,\nCloud Team" | msmtp --from=$EMAIL_USERNAME --host=smtp.hostinger.com --port=587 --auth=on --tls=on --user=$EMAIL_USERNAME --passwordeval "echo ${{ secrets.EMAIL_PASSWORD }}" "$EMAIL_TO"
          done < non_committers_7pm.txt

      - name: Send 9 AM Warning Email to Non-Committers
        if: github.event.schedule == '30 3 * * 1-5' && success() && hashFiles('final_non_committers.txt') != ''
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        run: |
          export LANG=en_US.UTF-8
          export LC_ALL=en_US.UTF-8
          while IFS= read -r user; do
            EMAIL_TO="yogesh.more@thedatatechlabs.com"
            printf "From: $EMAIL_USERNAME\nTo: $EMAIL_TO\nSubject: 🚨 Urgent: No Commit Yesterday!\n\nHello ${user},\n\nYou didn't commit yesterday, despite a reminder. Please take immediate action.\n\nRegards,\nCloud Team" | msmtp --from=$EMAIL_USERNAME --host=smtp.hostinger.com --port=587 --auth=on --tls=on --user=$EMAIL_USERNAME --passwordeval "echo ${{ secrets.EMAIL_PASSWORD }}" "$EMAIL_TO"
          done < final_non_committers.txt

      - name: Send Summary Report to Admin at 9 AM
        if: github.event.schedule == '30 3 * * 1-5' && success()
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        run: |
          RECIPIENT_EMAIL="yogesh.more@thedatatechlabs.com"
          NON_COMMITTED_LIST=$(cat final_non_committers.txt | tr '\n' ', ')
          
          printf "From: $EMAIL_USERNAME\nTo: $RECIPIENT_EMAIL\nSubject: Daily Commit Report - Non-Committers\n\nHello Team,\n\nThese users did not commit anything yesterday:\n\n$NON_COMMITTED_LIST\n\nRegards,\nCloud Team" | msmtp --from=$EMAIL_USERNAME --host=smtp.hostinger.com --port=587 --auth=on --tls=on --user=$EMAIL_USERNAME --passwordeval "echo ${{ secrets.EMAIL_PASSWORD }}" "$RECIPIENT_EMAIL"
