name: Check Recent Committers

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:  # Allows manual triggering

jobs:
  check-recent-committers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: List Collaborators and Check Recent Commit Activity
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MANAGER_USERNAME: "manager-username"  # Replace with actual manager's GitHub username
        run: |
          echo "Fetching Collaborators..."
          COLLABORATORS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/${{ github.repository }}/collaborators" \
               | jq -r '.[].login')
          
          echo "Collaborators List:"
          echo "$COLLABORATORS"
          
          echo "\nRecent Committers (Last Hour):"
          COMMITTED=false
          NON_COMMITTED_USERS=""
          COMMITTED_USERS=""
          
          for user in $COLLABORATORS; do
            if [ "$user" = "$MANAGER_USERNAME" ]; then
              continue  # Skip manager
            fi
            
            echo "Checking commits for: $user"
            RECENT_COMMITS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                 -H "Accept: application/vnd.github.v3+json" \
                 "https://api.github.com/repos/${{ github.repository }}/commits?author=$user&since=$(date -u -d '1 hour ago' +"%Y-%m-%dT%H:%M:%SZ")" \
                 | jq length)
            
            if [ "$RECENT_COMMITS" -gt 0 ]; then
              echo "$user committed in the last hour ($RECENT_COMMITS commits)"
              COMMITTED_USERS+="$user\n"
              COMMITTED=true
            else
              NON_COMMITTED_USERS+="$user\n"
            fi
          done
          
          if [ "$COMMITTED" = false ]; then
            echo "No one has committed in the last hour."
          fi
          
          echo "\nNon-Committers (Last Hour):"
          echo -e "$NON_COMMITTED_USERS"
