name: Notify Non-Committers via Mail - Test Mode

on:
  workflow_dispatch:
  schedule:
    - cron: "30 13 * * 1-5"  # 7:30 PM IST (13:30 UTC)
    - cron: "30 3 * * 1-5"   # 9:30 AM IST (03:30 UTC)

jobs:
  list-collaborators-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch Collaborators
        id: collaborators
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching Collaborators..."
          curl -s -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/${{ github.repository }}/collaborators" | jq -r '.[].login' | sort -u > collaborators.txt
          echo "Collaborators Fetched:"
          cat collaborators.txt

      - name: Fetch Today's Committers
        id: committers
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TODAY=$(date -u +"%Y-%m-%dT")
          echo "Fetching Committers..."
          curl -s -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/${{ github.repository }}/commits?since=${TODAY}00:00:00Z" | jq -r '.[].author.login' | sort -u > committers.txt
          echo "Committers Today:"
          cat committers.txt

      - name: Find Non-Committers
        id: non_committers
        run: |
          comm -23 <(sort -u collaborators.txt) <(sort -u committers.txt) > non_committers.txt
          echo "Non-Committers:" && cat non_committers.txt

      - name: Install and Configure msmtp
        run: |
          sudo apt-get update && sudo apt-get install -y msmtp
          cat <<EOF > ~/.msmtprc
          defaults
          auth           login
          tls            on
          tls_trust_file /etc/ssl/certs/ca-certificates.crt
          logfile        ~/.msmtp.log
          account hostinger
          host smtp.hostinger.com
          port 465
          user "${{ secrets.EMAIL_USERNAME }}"
          password "${{ secrets.EMAIL_PASSWORD }}"
          from "${{ secrets.EMAIL_USERNAME }}"
          account default : hostinger
          EOF
          chmod 600 ~/.msmtprc

      - name: Send Test Email (Manual Trigger Only)
        if: github.event_name == 'workflow_dispatch'
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        run: |
          EMAIL_TO="prathmesh.chikhale@tdtl.world"
          printf "From: $EMAIL_USERNAME\nTo: $EMAIL_TO\nSubject: 📩 Test Email for Notification Workflow\nMIME-Version: 1.0\nContent-Type: text/plain; charset=UTF-8\nContent-Transfer-Encoding: 8bit\n\nHello,\n\nThis is a test email to verify the email format before running the full workflow.\n\nBest,\nCloud Team" | msmtp "$EMAIL_TO"

      - name: Send 7 PM Reminder to Non-Committers
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        run: |
          while IFS= read -r user; do
            EMAIL_TO="yogesh.more@thedatatechlabs.com"
            echo "Sending reminder to $user" >> email_log.txt
            printf "From: $EMAIL_USERNAME\nTo: $EMAIL_TO\nSubject: ⚠️ Reminder - No Commit Today!\n\nHello ${user},\n\nPlease ensure you push your updates today.\n\nBest,\nCloud Team" | msmtp "$EMAIL_TO"
          done < non_committers.txt
