name: Test Email Notifications

on:
  workflow_dispatch:  # Allows manual execution
  schedule:
    - cron: '0 19 * * *'  # Runs at 7 PM UTC (Adjust if needed)
    - cron: '0 9 * * *'   # Runs at 9 AM UTC (Adjust if needed)

jobs:
  list-collaborators-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch Collaborators
        id: collaborators
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching Collaborators..."
          COLLABORATORS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                              -H "Accept: application/vnd.github.v3+json" \
                              "https://api.github.com/repos/${{ github.repository }}/collaborators" | jq -r '.[].login')
          echo "$COLLABORATORS" | sort -u > collaborators.txt
          echo "All Collaborators:"
          cat collaborators.txt

      - name: Find Collaborators Who Did Not Commit Today
        id: non_committers
        run: |
          echo "Finding Collaborators who did NOT commit today..."
          touch committers.txt  # Ensure file exists
          sort -u committers.txt > sorted_committers.txt
          comm -23 collaborators.txt sorted_committers.txt > non_committers.txt
          echo "Users who did NOT commit today:"
          cat non_committers.txt

      - name: Install and Configure msmtp
        run: |
          sudo apt-get update && sudo apt-get install -y msmtp
          echo "Creating msmtp config file..."
          cat <<EOF > ~/.msmtprc
          defaults
          auth           login
          tls            on
          tls_trust_file /etc/ssl/certs/ca-certificates.crt
          logfile        ~/.msmtp.log
          account hostinger
          host smtp.hostinger.com
          port 465
          user "${{ secrets.EMAIL_USERNAME }}"
          password "${{ secrets.EMAIL_PASSWORD }}"
          from "${{ secrets.EMAIL_USERNAME }}"
          account default : hostinger
          EOF
          chmod 600 ~/.msmtprc

      - name: Send 7 PM Reminder to Non-Committers
        if: github.event.schedule == '0 19 * * *'
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        run: |
          if [[ -s non_committers.txt ]]; then
            while IFS= read -r user; do
              EMAIL_TO="yogesh.more@thedatatechlabs.com"
              printf "From: $EMAIL_USERNAME\nTo: $EMAIL_TO\nSubject: ⚠️ Reminder - No Commit Today!\n\nHello ${user},\n\nPlease commit today.\n\nBest,\nCloud Team" | msmtp "$EMAIL_TO"
            done < non_committers.txt
          else
            echo "No users to notify."
          fi

      - name: Send 9 AM Follow-up to Non-Committers
        if: github.event.schedule == '0 9 * * *'
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        run: |
          if [[ -s non_committers.txt ]]; then
            while IFS= read -r user; do
              EMAIL_TO="yogesh.more@thedatatechlabs.com"
              printf "From: $EMAIL_USERNAME\nTo: $EMAIL_TO\nSubject: 🚨 Warning - No Commit Yesterday!\n\nHello ${user},\n\nImmediate action required—commit updates.\n\nRegards,\nCloud Team" | msmtp "$EMAIL_TO"
            done < non_committers.txt
          else
            echo "No users to notify."
          fi

      - name: Send Summary Email to Admins
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        run: |
          if [[ -s non_committers.txt ]]; then
            RECIPIENT_EMAIL="yogesh.more@thedatatechlabs.com"
            NON_COMMITTED_LIST=$(cat non_committers.txt | tr '\n' ', ')
            printf "From: $EMAIL_USERNAME\nTo: $RECIPIENT_EMAIL\nSubject: Daily Commit Report - Non-Committers Alert\n\nHello Team,\n\nUsers without commits:\n\n$NON_COMMITTED_LIST\n\nRegards,\nCloud Team" | msmtp "$RECIPIENT_EMAIL"
          else
            echo "No non-committers to report."
          fi
