name: Notify Non-Committers via Mail

on:
  workflow_dispatch:
  schedule:
    - cron: "30 13 * * 1-5"  # 7:30 PM IST (13:30 UTC)
    - cron: "30 3 * * 1-5"   # 9:30 AM IST (03:30 UTC) 

jobs:
  list-collaborators-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y jq msmtp

      - name: Fetch Collaborators
        id: collaborators
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching Collaborators..."
          COLLABORATORS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                              -H "Accept: application/vnd.github.v3+json" \
                              "https://api.github.com/repos/${{ github.repository }}/collaborators" | jq -r '.[].login')

          if [ -z "$COLLABORATORS" ]; then
            echo "Error: Failed to fetch collaborators"
            exit 1
          fi

          echo "$COLLABORATORS" > collaborators.txt

          # Define managers to exclude
          MANAGERS=("bhuse-vrushabh")  # Replace with actual usernames
          grep -vxF -f <(printf "%s\n" "${MANAGERS[@]}") collaborators.txt > temp.txt && mv temp.txt collaborators.txt
          echo "Filtered Collaborators: $(cat collaborators.txt)"

      - name: Fetch Today's Committers
        id: committers
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TODAY=$(date -u +"%Y-%m-%dT")
          echo "Fetching Users who committed today..."

          COMMITTERS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                             -H "Accept: application/vnd.github.v3+json" \
                             "https://api.github.com/repos/${{ github.repository }}/commits?since=${TODAY}00:00:00Z" | jq -r '.[].author.login' | sort -u)

          if [ -z "$COMMITTERS" ]; then
            echo "No commits found for today."
          fi

          echo "$COMMITTERS" > committers.txt
          echo "Today's Committers: $(cat committers.txt)"

      - name: Find Non-Committers
        id: non_committers
        run: |
          comm -23 <(sort collaborators.txt) <(sort committers.txt) > non_committers.txt
          echo "Non-Committers: $(cat non_committers.txt)"

      - name: Configure msmtp
        run: |
          cat <<EOF > ~/.msmtprc
          defaults
          auth           login
          tls            on
          tls_trust_file /etc/ssl/certs/ca-certificates.crt
          logfile        ~/.msmtp.log
          account hostinger
          host smtp.hostinger.com
          port 465
          user "${{ secrets.EMAIL_USERNAME }}"
          password "${{ secrets.EMAIL_PASSWORD }}"
          from "${{ secrets.EMAIL_USERNAME }}"
          account default : hostinger
          EOF
          chmod 600 ~/.msmtprc

      - name: Send 7 PM Reminder to Non-Committers
        if: github.event.schedule == '30 13 * * 1-5'
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        run: |
          while IFS= read -r user; do
            EMAIL_TO="yogesh.more@thedatatechlabs.com"
            echo -e "Subject: ⚠️ Reminder - No Commit Today!\n\nHello ${user},\n\nThis is a reminder that as of now, no commit has been recorded from your end in the repository today. Please ensure that you push your updates before the end of the day.\nIf there’s any issue preventing you from committing, let me know immediately.\n\nBest,\nCloud Team" | msmtp "$EMAIL_TO"
          done < non_committers.txt

      - name: Send Next Morning Follow-up to Non-Committers
        if: github.event.schedule == '30 3 * * 1-5'
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        run: |
          while IFS= read -r user; do
            EMAIL_TO="yogesh.more@thedatatechlabs.com"
            echo -e "Subject: 🚨 Warning - No Commit Yesterday!\n\nHello ${user},\n\nI have reviewed today's repository activity and noticed that you have not committed any updates. Please ensure your contributions are updated immediately.\nLet me know if there is any issue preventing you from completing your work.\n\nRegards,\nCloud Team" | msmtp "$EMAIL_TO"
          done < non_committers.txt

      - name: Send Summary Email to Admins
        if: github.event.schedule == '30 3 * * 1-5'
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        run: |
          RECIPIENTS="yogesh.more@thedatatechlabs.com"
          NON_COMMITTED_LIST=$(cat non_committers.txt | tr '\n' ', ')
          
          echo -e "Subject: 📊 Daily Commit Report\n\nHello Team,\n\nThe following users did not commit yesterday:\n\n$NON_COMMITTED_LIST\n\nPlease advise on the next steps if no action is taken.\n\nBest,\nCloud Team" | msmtp $(echo $RECIPIENTS | tr ',' ' ')
