name: Check Recent Committers and Notify Non-Committers

on:
  schedule:
    - cron: "30 13 * * 1-5"  # Runs at 7 PM IST (1:30 PM UTC) Monday to Friday
    - cron: "30 3 * * 1-5"  # Runs at 9 AM IST (3:30 AM UTC) Monday to Friday
  workflow_dispatch:  # Allows manual triggering

jobs:
  check-recent-committers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch Collaborators
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COLLABORATORS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/collaborators" | jq -r '.[].login' | grep -v -E "TDTL-Internal-Applications|ImranTDTL|Nikhil-Tdtl")
          echo "COLLABORATORS=$(echo $COLLABORATORS | tr '\n' ' ')" >> $GITHUB_ENV
      
      - name: Install and Configure msmtp
        run: |
          sudo apt-get update && sudo apt-get install -y msmtp
          cat <<EOF > ~/.msmtprc
          defaults
          auth           login
          tls            on
          tls_trust_file /etc/ssl/certs/ca-certificates.crt
          logfile        ~/.msmtp.log
          account hostinger
          host smtp.hostinger.com
          port 587
          user "${{ secrets.EMAIL_USERNAME }}"
          password "${{ secrets.EMAIL_PASSWORD }}"
          from "${{ secrets.EMAIL_USERNAME }}"
          account default : hostinger
          EOF
          chmod 600 ~/.msmtprc

      - name: Check Recent Commit Activity and Notify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EMAIL_USERNAME: "${{ secrets.EMAIL_USERNAME }}"
          MANAGER_EMAIL: "yogesh.more@thedatatechlabs.com"
        run: |
          CURRENT_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          SINCE_7PM_TIME=$(date -u -d 'yesterday 19:00:00' +"%Y-%m-%dT%H:%M:%SZ")
          SINCE_24H_TIME=$(date -u -d '24 hours ago' +"%Y-%m-%dT%H:%M:%SZ")
          
          NON_COMMITTERS=()
          REMINDED_USERS=()
          COMMITTERS=()

          for USER in $COLLABORATORS; do
            echo "Checking commits for: $USER"
            EMAIL_TO="yogesh.more@thedatatechlabs.com"

            API_URL="https://api.github.com/repos/${{ github.repository }}/commits?sha=main&author=$USER&since=$SINCE_24H_TIME"
            RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" "$API_URL")

            if echo "$RESPONSE" | jq empty 2>/dev/null; then
              COMMIT_COUNT=$(echo "$RESPONSE" | jq length)
              
              if [ "$COMMIT_COUNT" -eq 0 ]; then
                NON_COMMITTERS+=("$USER")

                if [ "${{ github.event.schedule }}" = "30 13 * * 1-5" ]; then
                  echo "Sending reminder email to $USER..."
                  printf "From: $EMAIL_USERNAME\nTo: $EMAIL_TO\nSubject: Reminder - No Commit Today!\n\nHello $USER,\n\nYou have not committed to the repository today. Please push your updates before the end of the day.\n\nBest,\nCloud Team" | msmtp "$EMAIL_TO"
                  REMINDED_USERS+=("$USER")
                fi
              else
                COMMITTERS+=("$USER")
              fi
            else
              echo "Error: Invalid API response for $USER"
              exit 1
            fi
          done

          if [ "${{ github.event.schedule }}" = "30 3 * * 1-5" ]; then
            FINAL_NON_COMMITTERS=()
            for USER in "${REMINDED_USERS[@]}"; do
              echo "Rechecking commits for: $USER"
              
              API_URL="https://api.github.com/repos/${{ github.repository }}/commits?sha=main&author=$USER&since=$SINCE_7PM_TIME"
              FINAL_COMMITS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                   -H "Accept: application/vnd.github.v3+json" "$API_URL" | jq length)

              if [ "$FINAL_COMMITS" -eq 0 ]; then
                echo "$USER still has not committed. Sending warning email..."
                EMAIL_TO="yogesh.more@thedatatechlabs.com"

                printf "From: $EMAIL_USERNAME\nTo: $EMAIL_TO\nSubject: WARNING - No Commit Detected!\n\nHello $USER,\n\nYou have not committed any updates. Immediate action is required.\n\nRegards,\nCloud Team" | msmtp "$EMAIL_TO"
                FINAL_NON_COMMITTERS+=("$USER")
              else
                echo "$USER committed after 7 PM. No email will be sent."
                COMMITTERS+=("$USER")
              fi
            done

            echo "Sending Daily Report to Manager..."
            printf "From: $EMAIL_USERNAME\nTo: $MANAGER_EMAIL\nSubject: Daily Commit Report\n\nHello Team,\n\nCommit Report for Today:\n\n✅ Committers:\n${COMMITTERS[*]}\n\n❌ Non-Committers:\n${FINAL_NON_COMMITTERS[*]}\n\nBest Regards,\nCloud Team" | msmtp "$MANAGER_EMAIL"
          fi
