name: Check Daily Commits and Notify Developers

on:
  schedule:
    - cron: "30 14 * * 1-5"  # Runs at 8 PM IST (2:30 PM UTC) Monday to Friday
  workflow_dispatch:  # Allows manual triggering

jobs:
  check-daily-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Fetch Collaborators
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COLLABORATORS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/collaborators" | jq -r '.[].login' | grep -v -E "TDTL-Internal-Applications|ImranTDTL|Nikhil-Tdtl")
          echo "COLLABORATORS=$(echo $COLLABORATORS | tr '\n' ' ')" >> $GITHUB_ENV
      
      - name: Install and Configure msmtp
        run: |
          sudo apt-get update && sudo apt-get install -y msmtp
          cat <<EOF > ~/.msmtprc
          defaults
          auth           login
          tls            on
          tls_trust_file /etc/ssl/certs/ca-certificates.crt
          logfile        ~/.msmtp.log
          account hostinger
          host smtp.hostinger.com
          port 587
          user "${{ secrets.EMAIL_USERNAME }}"
          password "${{ secrets.EMAIL_PASSWORD }}"
          from "${{ secrets.EMAIL_USERNAME }}"
          account default : hostinger
          EOF
          chmod 600 ~/.msmtprc
      
      - name: Check Daily Commit Activity and Notify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EMAIL_USERNAME: "${{ secrets.EMAIL_USERNAME }}"
        run: |
          SINCE_TIME=$(date -u -d '24 hours ago' +"%Y-%m-%dT%H:%M:%SZ")
          
          for USER in $COLLABORATORS; do
            EMAIL_TO="yogesh.more@thedatatechlabs.com"
            API_URL="https://api.github.com/repos/${{ github.repository }}/commits?sha=main&author=$USER&since=$SINCE_TIME"
            RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" "$API_URL")
            COMMIT_COUNT=$(echo "$RESPONSE" | jq length)
            
            if [ "$COMMIT_COUNT" -gt 0 ]; then
              echo "$USER has committed. Sending success email..."
              printf "From: $EMAIL_USERNAME\nTo: $EMAIL_TO\nSubject: Success - Commit Recorded!\n\nHello $USER,\n\nGreat job! Your commit has been successfully recorded in the repository today. Keep up the good work!\n\nMake sure to continue this streak and push your updates tomorrow as well. Consistency is key!\n\nBest,\nCloud Team" | msmtp "$EMAIL_TO"
              echo "Success email sent to: $EMAIL_TO"
            else
              echo "$USER has not committed. Sending reminder email..."
              printf "From: $EMAIL_USERNAME\nTo: $EMAIL_TO\nSubject: Reminder - No Commit Today!\n\nHello $USER,\n\nThis is a reminder that no commit has been recorded from your end today. Please ensure your updates are pushed before the end of the day.\n\nBest,\nCloud Team" | msmtp "$EMAIL_TO"
              echo "Reminder email sent to: $EMAIL_TO"
            fi
          done
