name: Alert Admin on File Deletion

on:
  push:
    branches:
      - main
      - frontend
      - backend

jobs:
  check_deletion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Ensure we get the previous commit
          
      - name: Install and Configure msmtp
        run: |
          echo "Creating msmtp config file..."
          cat <<EOF > ~/.msmtprc
          defaults
          auth           on
          tls            on
          tls_trust_file /etc/ssl/certs/ca-certificates.crt
          logfile        ~/.msmtp.log
          timeout        10   # Add a timeout to avoid infinite waiting
          account hostinger
          host smtp.hostinger.com
          port 465
          user "${{ secrets.EMAIL_USERNAME }}"
          password "${{ secrets.EMAIL_PASSWORD }}"
          from "${{ secrets.EMAIL_USERNAME }}"
          account default : hostinger
          EOF
          chmod 600 ~/.msmtprc
          
      - name: Check for Deleted Files
        id: check_deletions
        run: |
          # Get the previous commit
          previous_commit=$(git rev-parse HEAD^ 2>/dev/null || echo "")

          # Check if there is a previous commit
          if [ -n "$previous_commit" ]; then
            deleted_files=$(git diff --diff-filter=D --name-only $previous_commit HEAD)
          else
            deleted_files=""
          fi

          if [ -n "$deleted_files" ]; then
            echo "File deletion detected! Sending email alert."
            echo "deleted=true" >> $GITHUB_ENV
            echo "DELETED_FILES=$deleted_files" >> $GITHUB_ENV
          else
            echo "No files deleted."
            echo "deleted=false" >> $GITHUB_ENV
          fi

      - name: Send Email Notification to Admin
        if: env.deleted == 'true'
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        run: |
          ADMIN_EMAIL="pratham.chatke@thedatatechlabs.com"
          echo "Sending email alert to admin ($ADMIN_EMAIL)..."
        
          echo -e "Subject: ⚠️ Alert - File Deletion in Repository!\n\nHello Admin,\n\nThe following files were deleted:\n\n${{ env.DELETED_FILES }}\n\nDeleted by: ${{ env.DELETER }}\n\nPlease review the changes.\n\nBest,\nDevOps Team" \
            | msmtp --debug --from=$EMAIL_USERNAME --host=smtp.hostinger.com --port=465 --auth=on --tls=on --user=$EMAIL_USERNAME --passwordeval "echo ${{ secrets.EMAIL_PASSWORD }}" "$ADMIN_EMAIL"
