name: Test Commit Check and Email Notification

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  check-commits:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DEVELOPER_EMAIL: "yogesh.more@thedatatechlabs.com"
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
    steps:
      - name: Check for Commits in Last 5 Minutes
        id: check_commits
        run: |
          FIVE_MIN_AGO=$(date -u -d "5 minutes ago" +"%Y-%m-%dT%H:%M:%SZ")
          NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          
          echo "Checking commits from $FIVE_MIN_AGO to $NOW..."
          
          COMMIT_COUNT=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/commits?since=$FIVE_MIN_AGO&until=$NOW" \
            | jq 'length')
          
          echo "Commits found: $COMMIT_COUNT"
          
          if [ "$COMMIT_COUNT" -eq 0 ]; then
            echo "NO_COMMIT=true" >> $GITHUB_ENV
          else
            echo "NO_COMMIT=false" >> $GITHUB_ENV
          fi
      
      - name: Send Email if No Commit
        if: env.NO_COMMIT == 'true'
        run: |
          echo "No commits found. Sending email to developer."
          sudo apt-get update && sudo apt-get install -y msmtp
          
          cat <<EOF > ~/.msmtprc
          defaults
          auth           login
          tls            on
          tls_trust_file /etc/ssl/certs/ca-certificates.crt
          account hostinger
          host smtp.hostinger.com
          port 465
          user "${EMAIL_USERNAME}"
          password "${EMAIL_PASSWORD}"
          from "${EMAIL_USERNAME}"
          account default : hostinger
          EOF
          chmod 600 ~/.msmtprc
          
          printf "From: $EMAIL_USERNAME\nTo: $DEVELOPER_EMAIL\nSubject: No Commit in Last 5 Minutes\n\nNo commit has been made in the last 5 minutes. Please check." | msmtp --from=$EMAIL_USERNAME --host=smtp.hostinger.com --port=465 --auth=on --tls=on --user=$EMAIL_USERNAME --password=$EMAIL_PASSWORD "$DEVELOPER_EMAIL"
